/**
 * Site Factory Engine — Phase 2
 * Bulk site creation: domain → analysis → content → site record
 * Supports single creation and batch processing with progress callbacks.
 */

import { db } from '../db';
import { sites } from '@shared/schema';
import { eq } from 'drizzle-orm';
import { analyzeDomain, generateSiteContent, type DomainAnalysis, type SiteContent } from './mortgage-content-engine';

export interface SiteFactoryResult {
  domain: string;
  success: boolean;
  siteId?: number;
  pageCount?: number;
  analysis?: DomainAnalysis;
  error?: string;
}

export interface BatchProgress {
  total: number;
  completed: number;
  failed: number;
  current: string;
  results: SiteFactoryResult[];
}

export type ProgressCallback = (progress: BatchProgress) => void;

export interface CreateSiteOptions {
  userId: string;
  tenantId?: string;
  overrideTemplate?: string;
  skipIfExists?: boolean;
  generateAIContent?: boolean;
}

/**
 * Create a single site from a domain name.
 * Analyzes the domain, generates content, and inserts into the DB.
 */
export async function createSiteFromDomain(
  domain: string,
  options: CreateSiteOptions
): Promise<SiteFactoryResult> {
  const cleanDomain = domain.toLowerCase().trim().replace(/^https?:\/\//, '').replace(/\/$/, '');

  try {
    // Check for existing site
    if (options.skipIfExists) {
      const existing = await db.select({ id: sites.id })
        .from(sites)
        .where(eq(sites.domain, cleanDomain))
        .limit(1);
      if (existing.length > 0) {
        return { domain: cleanDomain, success: true, siteId: existing[0].id, error: 'already_exists' };
      }
    }

    // Analyze domain
    const analysis = analyzeDomain(cleanDomain);

    // Generate content (AI or template)
    const content = options.generateAIContent !== false
      ? await generateSiteContent(analysis)
      : null;

    const templateId = options.overrideTemplate || analysis.suggestedTemplateId;

    // Build site config
    const config = {
      title: content?.pageTitle || analysis.brandName,
      description: content?.metaDescription || `${analysis.brandName} — Mortgage lending${analysis.state ? ` in ${analysis.state}` : ''}.`,
      keywords: analysis.suggestedKeywords,
      primaryColor: '#1e3a5f',
      secondaryColor: '#e8b84b',
      phone: '',
      email: '',
      address: analysis.state ? `${analysis.state}, USA` : 'USA',
      licenseNumber: '',
      nmlsNumber: '1831233',
      statesLicensed: analysis.stateCode ? [analysis.stateCode] : [],
      loanTypes: analysis.loanTypes,
      customContent: content ? {
        heroHeadline: content.heroHeadline,
        heroSubheadline: content.heroSubheadline,
        heroCtaText: content.heroCtaText,
        aboutTitle: content.aboutTitle,
        aboutBody: content.aboutBody,
        servicesTitle: content.servicesTitle,
        services: JSON.stringify(content.services),
        faqTitle: content.faqTitle,
        faqs: JSON.stringify(content.faqs),
        ctaHeadline: content.ctaHeadline,
        ctaSubtext: content.ctaSubtext,
        footerTagline: content.footerTagline,
        pages: content.pages,
      } : {
        pages: [
          { slug: 'home', title: 'Home', content: '' },
          { slug: 'about', title: 'About Us', content: '' },
          { slug: 'contact', title: 'Contact Us', content: '' },
        ]
      },
    };

    const [inserted] = await db.insert(sites).values({
      domain: cleanDomain,
      name: analysis.brandName,
      templateId,
      category: analysis.niche === 'general' ? 'mortgage' : analysis.niche,
      status: 'draft',
      userId: options.userId,
      tenantId: options.tenantId ?? null,
      config: config as typeof sites.$inferInsert['config'],
      metaData: {
        niche: analysis.niche,
        state: analysis.state,
        stateCode: analysis.stateCode,
        city: analysis.city,
        autoGenerated: true,
        generatedAt: new Date().toISOString(),
      } as Record<string, unknown>,
    }).returning({ id: sites.id });

    return { 
      domain: cleanDomain, 
      success: true, 
      siteId: inserted.id, 
      pageCount: config.customContent.pages.length,
      analysis 
    };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return { domain: cleanDomain, success: false, error: msg };
  }
}

/**
 * Batch-create sites from a list of domains.
 * Calls onProgress after each domain so callers can stream updates.
 */
export async function batchDeployDomains(
  domains: string[],
  options: CreateSiteOptions,
  onProgress?: ProgressCallback
): Promise<BatchProgress> {
  const progress: BatchProgress = {
    total: domains.length,
    completed: 0,
    failed: 0,
    current: '',
    results: [],
  };

  for (const domain of domains) {
    progress.current = domain;
    onProgress?.(progress);

    const result = await createSiteFromDomain(domain, {
      ...options,
      skipIfExists: options.skipIfExists ?? true,
    });

    progress.results.push(result);
    if (result.success) progress.completed++;
    else progress.failed++;

    onProgress?.(progress);
  }

  progress.current = '';
  onProgress?.(progress);
  return progress;
}

/**
 * Parse a newline/comma-separated domain list string into clean domain array.
 */
export function parseDomainList(raw: string): string[] {
  return raw
    .split(/[\n,;]+/)
    .map(d => d.trim().toLowerCase().replace(/^https?:\/\//, '').replace(/\/$/, ''))
    .filter(d => d.length > 3 && d.includes('.'));
}

/**
 * Get a summary of all sites for a user with factory metadata.
 */
export async function getSitesSummary(userId: string) {
  const userSites = await db.select({
    id: sites.id,
    domain: sites.domain,
    name: sites.name,
    templateId: sites.templateId,
    category: sites.category,
    status: sites.status,
    seoScore: sites.seoScore,
    leadCount: sites.leadCount,
    createdAt: sites.createdAt,
    metaData: sites.metaData,
  })
  .from(sites)
  .where(eq(sites.userId, userId))
  .orderBy(sites.createdAt);

  return userSites;
}
